# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_example'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectionR',
            new_name='SectionRight',
        ),
    ]
