# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20171219_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='author',
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
